name: SCAR
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311hdb19cb5_0
  - debugpy=1.8.13=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.0.0=pyhfb0248b_1
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h767d61c_2
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.10.1=py311hd28fd6d_0
  - numpy-base=2.0.1=py311hbfb1bba_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2024.1=py311h06a4308_0
  - pyzmq=26.2.1=py311h7deb3e3_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.15.2=py311h210a465_1
  - seaborn=0.13.2=py311h06a4308_2
  - setuptools=75.1.0=py311h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h9ecbd09_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - astunparse==1.6.3
      - basicsr==1.4.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cycler==0.12.1
      - einops==0.8.1
      - facexlib==0.3.0
      - filelock==3.16.1
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2024.10.0
      - future==1.0.0
      - gast==0.6.0
      - gfpgan==1.3.8
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.13.0
      - huggingface-hub==0.29.3
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.4
      - keras==3.9.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - pillow==11.0.0
      - protobuf==5.29.1
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - requests==2.32.3
      - responses==0.25.3
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - sympy==1.13.1
      - tb-nightly==2.20.0a20250402
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - tf-keras==2.19.0
      - tifffile==2025.3.30
      - timm==1.0.15
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yapf==0.43.0
